---
title: "Careers"
output: html_document
---

<br>

### Postdoctoral Associate in Functional Genomics

The Jin Lab is seeking a talented and enthusiastic postdoctoral fellow to join our growing team in the Department of Genetics at Washington University School of Medicine. The postdoctoral fellow will be jointly advised by investigators Sheng Chih Jin, Kristopher Kahle (Assistant Professor of Neurosurgery and Pediatrics and Cellular and Molecular Physiology at Yale School of Medicine) and Yi-Hsien Chen (Assistant Director of the Genome Engineering & iPSC Center). To tackle central questions about the pathophysiology of congenital hydrocephalus, moyamoya disease, and/or congenital heart disease, the fellow will conduct functional genomics research under the guiding aims:

* Characterization of biological mechanisms disrupted by pathogenic mutations
* Development of human disease models using human-induced pluripotent stem cell and/or zebrafish model systems
* Implementation of multi-omics approach that integrate high-throughput imaging and machine learning coupled with CRISPR/Cas9 screens

Our interdisciplinary research environment brings together life scientists, computational biologists, and physician-scientists to identify mutations underlying human diseases and their pathogenic mechanisms with the ultimate goal of translating these findings into effective therapeutic treatments. For more information, please visit our lab webpages: https://scjin.github.io/, https://www.kahlelab.com/, and http://geic.wustl.edu/

Required qualifications:

* Recent PhD/MD in a biological sciences or related fields (Molecular Biology, Developmental Biology, Cell Biology, Neurosciences, Biochemistry, etc.)
* Experience in the zebrafish handling, cell culture, neuroscience, and genomics
* Good communication skills
* In addition, applicants must be able to visit St. Louis for potential interviews

Applicants should email a single PDF file consisting of a letter of interest and CV, and should arrange for three letters of reference to be sent to Dr. Jin (jin810@wustl.edu), Dr. Kahle (kristopher.kahle@yale.edu) and Dr. Chen (ychen5@wustl.edu)

-----

### Postdoctoral Associate in Computational Genomics ([WashU Job ID](https://jobs.wustl.edu/): 46784)

The Jin lab is looking for an energetic and motivated individual to work as a Postdoctoral Associate with a doctoral degree in genetics, genomics, computational biology, or computer science to investigate the genetic basis of congenital heart disease, hydrocephalus, and Moyamoya disease.

Although advances in next-generation sequencing have discovered the genetic causes of a large proportion of patients with congenital disorders,the etiology of most cases remains unclear. It is becoming evident that simple genetic models do not entirely explain the causes of all congenital disorders and more nuanced approaches are required. Therefore, the Jin lab's research is focusing on the formulation and development of computational methods to determine the complex genetic basis underlying congenital disorders using human genetics, genomics, and advanced statistical methods. Our goal is to translate an improved molecular understanding of congenital disorders from the laboratory into clinically actionable models, diagnostics, and ultimately therapeutic interventions.

We are currently looking for researchers with a strong computational background in genomic and functional genomic analysis, including whole exome/genome sequencing, large scale genetic association studies, and integrative analysis of genomic and functional genomic data. The candidate will be expected to plan and carry out research tasks independently and write-up/present findings on a regular basis.

The Jin lab is located in the Couch Biomedical Research building on the 5th floor in the Department of Genetics space. The successful candidate will take advantage of the unique collaborative relationships with the McDonnell Genome Institute, the Intellectual and Developmental Disabilities Research Center, Departments of Pediatrics & Neuroscience, and across the broader research community of Washington University which provides outstanding training and educational opportunities. Dr. Jin is committed to mentoring and training the candidate, providing all the support the candidate needs to reach their career goals. For competitive candidates, references from current and previous trainees attesting to the supportive and dynamic research environment of the Jin lab are available upon request.

To be considered for this role, please email Dr. Jin at jin810@wustl.edu with the following items: 1) CV with a list of publications; 2) a short summary of your present and future research interests; 3) a list of three references with their contact information. Diverse expertise will be considered. Competitive salary and benefits will be provided

-----

### Bioinformatics Research Analyst/Bioinformatics Scientist ([WashU Job ID](https://jobs.wustl.edu/): 46782)

We are looking for a computational biologist, software engineer, or bioinformatician with extensive experience in developing cutting edge tools to analyze high-throughput sequencing-based experiments, including but not limited to whole exome/genome sequencing, RNA-sequencing, single-cell RNA-sequencing, ChIP-sequencing, and ATAC-sequencing. Responsibilities include use of existing bioinformatics tools to process sequence data (alignment, variant calling, etc.), producing visualizations that aid interpretation of large data sets working with software developers to release open access bioinformatics tools, and contributing to publications and educational workshops.

Primary Duties:

* Designs, develops, and implements
	+ Standard next-generation sequencing (NGS) analysis software (e.g. samtools, BWAMEM, GATK, Picard, bedtools, FreeBayes)
	+ Management/annotation/analysis of genomic datasets (e.g. Plink, HAIL, BCFtools, Annovar, SnpEff) and cloud computing platform (e.g. AWS, Google Cloud)
	+ Relational databases to store, disseminate and analyze data, including verification of data submitted and recommendations for analyses
	+ Web interfaces and queries to access relational databases; maintains web server
* Performs complex systems analysis of data and writes interpretative reports
* Evaluates commercial and academic bioinformatics software
* Trains other researchers on the everyday use of analysis software and research databases
* Assists with grant preparation and reporting of methods, data, and results
* Solves practical problems relating to difficulties with equipment or test subjects; suggests technical or procedural improvements in testing methods

Qualifications:

* Bachelor's or Master’s degree in Computer Science or related field, or equivalent experience.
* 2-5 years of Software Development experience is preferred, though exceptional candidates with less will be considered.
* Experience delivering clear, maintainable, and well-tested software in a timely manner.
* Familiarity with big data processing pipelines (e.g. Google Pipelines API, WDL, CWL, Docker).
* Experience troubleshooting complex distributed systems.
* Experience working in unix/linux environments, including basic shell scripting.
* Experience with a formal programming language (e.g. Python or C++) and a statistical package (R or Matlab).
* Programming skills in Java and SQL a plus.
* Training in statistics or machine learning a plus.
* Team oriented with excellent written and verbal communication skills.

Competitive salary and benefits will be provided. If you are interested in this position, please email your CV to Dr. Jin at jin810@wustl.edu for discussion.

-----

### Graduates, Undergraduates, Summer Interns and Visiting Scholars

If you are a graduate/undergraduate student or a visiting scholar and looking for temporary lodging, please email your CV to Dr. Jin at jin810@wustl.edu for discussion.
