---
pagetitle: "Jin group"
---
<link rel="stylesheet" href="styles.css" type="text/css">



<br><br>

Welcome to the Jin group in the [Department of Genetics](http://genetics.wustl.edu/) and the [McDonnell Genome Institute](https://www.genome.wustl.edu/) at the Washington University School of Medicine. Our mission is to provide meaningful and interpretable insight into disease biology, and define new targets for risk determination, prevention, and therapy. We are currently focusing on the formation, development, and application of genetic, genomics, and bioinformatics methods to better analyze and integrate exome and genome sequencing, SNP array, RNA-sequencing, epigenomic, metabolomic, and proteomics data. Through integration of diverse type of transcriptomic and epigenetic functional annotations, the integrative genomic analysis will provide better a understanding of the molecular basis of cardiovascular diseases and neurodevelopmental disorders, with a specific focus on the interplay between rare protein-coding and common non-coding variants. 

We collaborate with clinicians, the [Pediatric Cardiac Genomics Consortium](https://benchtobassinet.com/?page_id=36), the [International Cerebral Palsy Genomics Consortium](https://icpgc.org/), and the [Yale Center for Mendelian Genomics](https://medicine.yale.edu/keck/ycga/) to assemble thoroughly phenotyped cohorts for gene discovery. We also collaborate with experimentalists to design scalable high-throughput assays to model effects of disease-associated mutations. If you think any of this sounds cool consider [joining us](./careers.html) in working to make the world a better place. If you just want to keep up with everything we are working on, follow Peter on Twitter https://twitter.com/peterjin.

