---
title: "Publications"
output: html_document
---

<br>

[NCBI Bibliography](https://www.ncbi.nlm.nih.gov/myncbi/sheng%20chih.jin.1/bibliography/public/)

Lab members in **bold**.

### Featured publications

**Tang Z#**, Ovunc SS#, **Mehinovic E**, Thomas S, **Ulibarri J**, **Li Z**, Baldridge D, Cruchaga C, Johnson M, Milbrandt J, Callaghan B, PNRR Study Group, Höke A&, Todd PK&, **Jin SC&**. [Heterozygous and Homozygous RFC1 AAGGG Repeat Expansions are Common in Idiopathic Peripheral Neuropathy](https://www.medrxiv.org/content/10.1101/2025.04.18.25325809v2). ***medRxiv***. #Equal contribution; &Co-corresponding authors. 

**Choi J#**, **Tang Z#**, **Dong W**, **Ulibarri J**, **Mehinovic E**, Thomas S, Höke A, **Jin SC**. 2025. [Unleashing the power of multi-omics: unraveling the molecular landscape of peripheral neuropathy](https://onlinelibrary.wiley.com/doi/full/10.1002/acn3.70019). ***Annals of Clinical and Translational Neurology***. #Equal contribution

Allington G#, Mehta NH#, Dennis E#, Mekbib KY#, Reeves B, Kiziltug E, Chen S, **Zhao S**, Duy PQ, Saleh M, Ang LC, Fan B, Nelson-Williams C, Moreno-de-Luca A, Haider S, Lifton RP, Alper SL, McGee S&, **Jin SC&**, Kahle KT&. 2024. [De novo variants disrupt an LDB1-regulated transcriptional network in congenital ventriculomegaly](https://academic.oup.com/brain/advance-article-abstract/doi/10.1093/brain/awae395/7925765?redirectedFrom=PDF). ***Brain***. #Equal contribution; &Co-corresponding authors.


Lewis SA#, **Ruttenberg A#**, **Iyiyol T**, **Kong N**, **Jin SC&**, Kruer MC&. 2024. [Potential clinical applications of advanced genomic analysis in cerebral palsy](https://www.sciencedirect.com/science/article/pii/S2352396424002640). ***eBioMedicine***. #Co-first authors; &Co-corresponding authors.

Duy PQ#, Jux Bettina#, **Zhao S#**, Mekbib KY, Dennis E, Dong W, Nelson-Williams C, Mehta NH, Shohfi JP, Juusola J, Allington G, Smith H, Marlin S, Belhous K, Estrada-Veras JI, Keren B, Mignot C, Flore LA, Palafoll IV, Alper SL, Lifton RP, Haider S, Moreno-De-Luca A, **Jin SC&**, Kolanus W&, Kahle KT&. 2024. [TRIM71 mutations cause a neurodevelopmental syndrome featuring ventriculomegaly and hydrocephalus](https://academic.oup.com/brain/advance-article/doi/10.1093/brain/awae175/7687707). ***Brain***. #Equal contribution; &Co-corresponding authors.

**Zhao S#**, Mekbib KY#, van der Ent MA#, Allington G#, Prendergast A, Chau JE, Smith H, Shohfi J, Ocken J, Duran D, Furey CG, Hao LT, Duy PQ, Reeves BC, Zhang J, Nelson-Williams C, Chen D, Li B, Nottoli T, Bai S, Rolle M, Zeng X, Dong W, **Fu P-Y**, **Wang Y-C**, Mane S, Piwowarczyk P, Fehnel KP, See AP, Iskandar BJ, Aagaard-Kienitz B, Moyer QJ, Dennis E, Kiziltug E, Kundishora AJ, DeSpenza T Jr, Greenberg ABW, Kidanemariam SM, Hale AT, Johnston JM, Jackson EM, Storm PB, Lang SS, Butler WE, Carter BS, Chapman P, Stapleton CJ, Patel AB, Rodesch G, Smajda S, Berenstein A, Barak T, Erson-Omay EZ, Zhao H, Moreno-De-Luca A, Proctor MR, Smith ER, Orbach DB, Alper SL, Nicoli S, Boggon TJ, Lifton RP, Gunel M, King PD&, **Jin SC&**, Kahle KT&. 2023. [Mutation of key signaling regulators of cerebrovascular development in vein of Galen malformations](https://www.nature.com/articles/s41467-023-43062-z). ***Nature Communications***. #Equal contribution; &Corresponding author

Kundishora AJ#, Allington G#, McGee S#, Mekbib KY#, Gainullin V, Timberlake AT, Nelson-Williams C, Kiziltug E, Smith H, Ocken J, Shohfi J, Allocco AA, Duy PQ, Elsamadicy A, Dong W, **Zhao S**, **Wang Y-C**, Qureshi H, Diluna ML, Mane S, Tikhonova IR, **Fu P-Y**, Castaldi C, López-Giráldez F, Knight JR, Furey CG, Carter BS, Haider S, Moreno-De-Luca A, Alper SL, Gunel M, Millan F, Lifton RP, Torene RI#, **Jin SC#**, Kahle KT#&. 2023. [Multi-omic analyses implicate a neurodevelopmental program in the pathogenesis of cerebral arachnoid cysts](https://www.nature.com/articles/s41591-023-02238-2). ***Nature Medicine***. #Equal contribution; &Corresponding author 

**Wang Y-C#**, Wu Y#, **Choi J#**, Allington G#, **Zhao S#**, **Khanfar M#**, **Yang K#**, **Fu P-Y**, **Wrubel M**, **Yu X**, Mekbib KY, Ocken J, Smith H, Shohfi J, Kahle KT, Lu Q&, **Jin SC&**. 2022. [Computational genomics in the era of precision medicine: applications to variant analysis and gene therapy](https://www.mdpi.com/2075-4426/12/2/175).  ***Journal of Personalized Medicine***. #Co-first authors; &Co-corresponding authors. [**Feature paper**]

Allington G, Duy PQ, **Ryou J**, Singh A, Kiziltug E, Robert SM, Kundishora A, **King S**, Haider S, Kahle KT, **Jin SC**. 2021. [Genomic approaches to improve the clinical diagnosis and management of congenital hydrocephalus patients](https://thejns.org/pediatrics/view/journals/j-neurosurg-pediatr/aop/article-10.3171-2021.8.PEDS21368/article-10.3171-2021.8.PEDS21368.xml). ***Journal of Neurosurgery:Pediatrics***.

Diab NS#, Barish S#, Dong W#, **Zhao S#**, Allington G, **Yu X**, Kahle KT, Brueckner M&, **Jin SC&**. 2021. [Molecular genetics and complex inheritance of congenital heart disease](https://www.mdpi.com/2073-4425/12/7/1020). ***Genes***. #Co-first authors; &Co-corresponding authors. [**Cover story**](https://www.mdpi.com/2073-4425/12/7?utm_campaign=releaseissue_genesutm_medium=emailutm_source=releaseissueutm_term=coverlink).

Kundishora AJ#, **Peters ST#**, Pinard A, Duran D, Panchagnula S, Barak T, Miyagishima DF, Dong W, Smith H, Ocken J, Dunbar A, Nelson-Williams C, Haider S, Walker RL, Li B, Zhao H, Thumkeo D, Marlier A, Duy PQ, Diab NS, Reeves BC, Robert SM, Sujijantarat N, Stratman AN, Chen Y-H, **Zhao S**, Roszko I, Lu Q, Zhang B, Mane S, Castaldi C, López-Giráldez F, Knight JR, Bamshad MJ, Nickerson DA, Geschwind DH, Lang Chen S-S, Storm PB, Diluna ML, Matouk C, Orbach DB, Alper SL, Smith ER, Lifton RP, Gunel M, Milewicz DM, **Jin SC&**, Kahle KT&. 2021. [DIAPH1 mutations in non-East Asian patients with sporadic moyamoya disease](https://jamanetwork.com/journals/jamaneuroly/fullarticle/2781029). ***JAMA Neurology***. #Co-first authors; &Co-corresponding authors.

Diab NS#, **King S#**, Dong W#, Allington G, Sheth A, **Peters S**, Kahle KT&, **Jin SC&**. 2021. [Analysis workflow to assess de novo genetic variants from whole-exome sequencing](https://star-protocols.cell.com/protocols/514?fbclid=IwAR0RAxAiY1LbdBXWdlWDL_fcfKIx7gzABfPn4F8tEs_VobHYDdmWO2iqJKY). ***STAR Protocols***. #Co-first authors; &Co-corresponding authors.

**Jin SC#**, Dong W#, Kundishora AJ#, Panchagnula S#, Moreno-De-Luca A#, Furey CG, Allocco AA, Walker RL, Nelson-Williams C, Smith H, Dunbar A, Conine S, Lu Q, Zeng X, Sierant MC, Knight JR, Sullivan W, Duy PQ, DeSpenza T, Reeves BC, Karimy JK, Marlier A, Castaldi C, Tikhonova IR, Li B, Peña HP, Broach JR, Kabachelor EM, Ssenyonga P, Hehnly C, Ge L, Keren B, Timberlake AT, Goto J, Mangano FT, Johnston JM, Butler WE, Warf BC, Smith ER, Schiff SJ, Limbrick DD, Heuer G, Jackson EM, Iskandar BJ, Mane S, Haider S, Guclu B, Bayri Y, Sahin Y, Duncan CC, Apuzzo ML, DiLuna ML, Hoffman EJ, Sestan N, Ment LR, Alper SL, Bilguvar K, Geschwind DH, Günel M, Lifton RP, Kahle KT. 2020. [Exome sequencing implicates genetic disruption of prenatal neuro-gliogenesis in sporadic congenital hydrocephalus](https://www.nature.com/articles/s41591-020-1090-2). ***Nature Medicine***. #Co-first authors .\
**Press coverage:** [Nature Medicine](https://www.nature.com/articles/s41591-020-1120-0), [Faculty Opinions](https://facultyopinions.com/prime/738854794), [Yale News](https://medicine.yale.edu/news-article/28466/)

**Jin SC#**, Lewis S#, Bakhtiari S#, Zeng X#, Sierant MC, Shetty S, Nordlie S, Elie A, Corbett M, Norton B, van Eyk C, Haider S, Guida B, Magee H, Liu J, Pastore S, Vincent J, Brunstrom-Hernandez J, Papavasileiou A, Fahey M, Berry J, Harper K, Zhou C, Zhang J, Li B, Heim J, Webber D, Frank M, Xia L, Xu Y, Zhu D, Zhang B, Sheth A, Knight JR, Castaldi C, Tikhonoa I, Lopez-Giraldez F, Keren B, Whalen S, Buratti J, Doummar D, Cho M, Retterer K, Millan F, Wang Y, Waugh J, Rodan L, Cohen J, Fatemi A, Lin A, Phillips J, Feyma T, MacLennan S, Vaughan S, Crompton K, Reid S, Reddihough D, Shang Q, Gao C, Novak I, Badawi N, Wilson Y, McIntyre S, Mane S, Wang X, Amor D, Zarnescu D, Lu Q, Xing Q†, Zhu C†, Bilguvar K, Padilla-Lopez S, Lifton RP, Gecz J, MacLennan A, Kruer MC. 2020 [Mutations disrupting neuritogenesis genes confer risk for cerebral palsy](https://www.nature.com/articles/s41588-020-0695-1). ***Nature Genetics***. #Co-first authors .\
**Press coverage:** [NIH](https://www.nih.gov/news-events/news-releases/about-14-cerebral-palsy-cases-may-be-tied-brain-wiring-genes), [WashU News](https://medicine.wustl.edu/news/cerebral-palsy-also-has-genetic-underpinnings/), [AJMG News](https://onlinelibrary.wiley.com/doi/epdf/10.1002/ajmg.a.61646)

Duran D#, Zeng X#, **Jin SC#**, Choi J, Nelson-Williams C, Yatsula B, Gaillard J, Furey CG, Lu Q, Timberlake AT, Dong W, Sorscher MA, Loring E, Klein J, Allocco A, Hunt A, Conine S, Karimy JK, Youngblood MW, Zhang J, DiLuna ML, Matouk CC, Mane S, Tikhonova IR, Castaldi C, López-Giráldez F, Knight J, Haider S, Soban M, Alper SL, Komiyama M, Ducruet AF, Zabramski JM, Dardik A, Walcott BP, Stapleton CJ, Aagaard-Kienitz B, Rodesch G, Jackson E, Smith ER, Orbach DB, Berenstein A, Bilguvar K, Vikkula M, Gunel M, Lifton RP, Kahle KT. 2019. [Mutations in chromatin modifier and Ephrin signaling genes in Vein of Galen malformation](https://www.sciencedirect.com/science/article/pii/S089662731831050X?via%3Dihub). ***Neuron***. #Co-first authors .\
**Press coverage:** [Yale News](https://yaledailynews.com/blog/2019/01/15/study-identifies-mutation-for-rare-infant-brain-disease/) 

**Jin SC#**, Homsy J#, Zaidi S#, Lu Q, Morton S, DePalma SR, Zeng X, Qi H, Chang W, Sierant MC, Hung WC, Haider S, Zhang J, Knight J, Bjornson RD, Castaldi C, Tikhonoa IR, Bilguvar K, Mane SM, Sanders SJ, Mital S, Russell MW, Gaynor JW, Deanfield J, Giardini A, Porter GA Jr, Srivastava D, Lo CW, Shen Y, Watkins WS, Yandell M, Yost HJ, Tristani-Firouzi M, Newburger JW, Roberts AE, Kim R, Zhao H, Kaltman JR, Goldmuntz E, Chung WK, Seidman JG, Gelb BD, Seidman CE, Lifton RP, Brueckner M. 2017. [Contribution of rare inherited and de novo variants in 2,871 congenital heart disease probands](https://www.nature.com/articles/ng.3970). ***Nature Genetics***. #Co-first authors. **[>700 cites]** .\
**Press coverage:** [New Haven Register](https://www.nhregister.com/news/article/Study-revealing-links-between-heart-disease-and-12264612.php), [MedicineNet](https://www.medicinenet.com/script/main/art.asp?articlekey=207467) 

### 2025

90 Sierant MC, **Jin SC**, Bilguvar K, Morton SU, Dong W, Jiang W, Lu Z, Li B, López-Giráldez F, Tikhonova I, Zeng X, Lu Q, Choi J, Zhang J, Nelson-Williams C, Knight JR, Zhao H, Cao J, Mane S, Sedore SC, Gruber PJ, Lek M, Goldmuntz E, Deanfield J, Giardini A, Mital S, Russell M, Gaynor JW, King E, Wagner M, Srivastava D, Shen Y, Bernstein D, Porter Jr GA, Newburger JW, Seidman JG, Roberts AE, Yandell M, Yost HJ, Tristani-Firouzi M, Kim R, Chun WK, Gelb BD, Seidman CE, Brueckner M, Lifton RP. [Genomic analysis of 11,555 probands identifies 60 dominant congenital heart disease genes](https://www.pnas.org/doi/10.1073/pnas.2420343122). ***PNAS***

89 Dong W, **Jin SC**, Sierant MC, Lu Z, Li B, Lu Q, Morton SU, Zhang J, López-Giráldez F, Nelson-Williams C, Knight J, Zhao H, Cao J, Mane S, Gruber PJ, Lek M, Goldmuntz E, Deanfield J, Giardini A, Mital S, Russell M, Gaynor JW, Cnota JF, Wagner M, Srivastava D, Bernstein D, Porter, Jr GA, Newburger J, Roberts AE, Yandell M, Yost HJ, Tristani-Firouzi M, Kim R, Seidman J, Chung WK, Gelb BD, Seidman CE, Lifton RP&, Brueckner M&. [Recessive genetic contribution to congenital heart disease in 5,424 probands](https://www.pnas.org/doi/10.1073/pnas.2419992122). ***PNAS*** &Co-corresponding authors.

88 DeSpenza T Jr#, Kiziltug E#, Allington G#, Barson DG#, McGee S, O'Connor D, Robert SM, Mekbib KY, Nanda P, Greenberg ABW, Singh A, Duy PQ, Mandino F, **Zhao S**, Lynn A, Reeves BC, Marlier A, Getz SA, Nelson-Williams C, Shimelis H, Walsh LK, Zhang J, Wang W, Prina ML, OuYang A, Abdulkareem AF, Smith H, Shohfi J, Mehta NH, Dennis E, Reduron LR, Hong J, Butler W, Carter BS, Deniz E, Lake EMR, Constable RT, Sahin M, Srivastava S, Winden K, Hoffman EJ, Carlson M, Gunel M, Lifton RP, Alper SL, **Jin SC**, Crair MC, Moreno-De-Luca A, Luikart BW&, Kahle KT&. [PTEN mutations impair CSF dynamics and cortical networks by dysregulating periventricular neural progenitors](https://www.nature.com/articles/s41593-024-01865-3). ***Nature Neuroscience*** #Equal contribution; &Co-corresponding authors.

87 **Choi J#**, **Tang Z#**, **Dong W**, **Ulibarri J**, **Mehinovic E**, Thomas S, Höke A, **Jin SC**. [Unleashing the power of multi-omics: unraveling the molecular landscape of peripheral neuropathy](https://onlinelibrary.wiley.com/doi/full/10.1002/acn3.70019). ***Annals of Clinical and Translational Neurology***. #Equal contribution


### 2024

86 Allington G#, Mehta NH#, Dennis E#, Mekbib KY#, Reeves B, Kiziltug E, Chen S, **Zhao S**, Duy PQ, Saleh M, Ang LC, Fan B, Nelson-Williams C, Moreno-de-Luca A, Haider S, Lifton RP, Alper SL, McGee S&, **Jin SC&**, Kahle KT&. [De novo variants disrupt an LDB1-regulated transcriptional network in congenital ventriculomegaly](https://academic.oup.com/brain/advance-article-abstract/doi/10.1093/brain/awae395/7925765?redirectedFrom=PDF). ***Brain***. #Equal contribution; &Co-corresponding authors.

85 Lewis SA#, **Ruttenberg A#**, **Iyiyol T**, **Kong N**, **Jin SC&**, Kruer MC&. [Potential clinical applications of advanced genomic analysis in cerebral palsy](https://www.sciencedirect.com/science/article/pii/S2352396424002640). ***eBioMedicine***. #Co-first authors; &Co-corresponding authors.

84 DeSpenza T Jr#, Singh A#, Allington G#, **Zhao S#**, Lee J#, Kizlitug E#, Prina ML, Desmet N, Dang HQ, Fields J, Nelson-Williams C, Zhang J, Mekbib KY, Dennis E, Mehta NH, Duy PQ, Shimelis H, Walsh LK, Marlier A, Deniz E, Lake EMR, Constable RT, Hoffman EJ, Lifton RP, Gulledge A, Fiering S, Moreno-De-Luca A, Haider S, Alper SL, **Jin SC**, Kahle K&, Luikart BW&. [Pathogenic variants in autism gene KATNAL2 cause hydrocephalus and disrupt neuronal connectivity by impairing ciliary microtubule dynamics](https://www.pnas.org/doi/10.1073/pnas.2314702121). ***PNAS***.  #Co-first authors; &Co-corresponding authors.

83 Duy PQ#, Jux Bettina#, **Zhao S#**, Mekbib KY, Dennis E, Dong W, Nelson-Williams C, Mehta NH, Shohfi JP, Juusola J, Allington G, Smith H, Marlin S, Belhous K, Estrada-Veras JI, Keren B, Mignot C, Flore LA, Palafoll IV, Alper SL, Lifton RP, Haider S, Moreno-De-Luca A, **Jin SC&**, Kolanus W&, Kahle KT&. [TRIM71 mutations cause a neurodevelopmental syndrome featuring ventriculomegaly and hydrocephalus](https://academic.oup.com/brain/advance-article/doi/10.1093/brain/awae175/7687707). ***Brain***.  #Co-first authors; &Co-corresponding authors.


82 Tafaleng EN, Li J, Wang Y, Hidvegi T, Soto-Gutierrez A, Locke AE, Nicholas TJ, **Wang Y-C**, Pak S, Cho MH, Silverman EK, Silverman GA, **Jin SC**, Fox IJ, Perlmutter DH. [Variants in autophagy genes MTMR12 and FAM134A are putative modifiers of the hepatic phenotype in α1-antitrypsin deficiency](https://journals.lww.com/hep/abstract/9900/variants_in_autophagy_genes_mtmr12_and_fam134a_are.833.aspx). ***Hepatology***.  

### 2023

81 **Zhao S#**, Mekbib KY#, van der Ent MA#, Allington G#, Prendergast A, Chau JE, Smith H, Shohfi J, Ocken J, Duran D, Furey CG, Hao LT, Duy PQ, Reeves BC, Zhang J, Nelson-Williams C, Chen D, Li B, Nottoli T, Bai S, Rolle M, Zeng X, Dong W, **Fu P-Y**, **Wang Y-C**, Mane S, Piwowarczyk P, Fehnel KP, See AP, Iskandar BJ, Aagaard-Kienitz B, Moyer QJ, Dennis E, Kiziltug E, Kundishora AJ, DeSpenza T Jr, Greenberg ABW, Kidanemariam SM, Hale AT, Johnston JM, Jackson EM, Storm PB, Lang SS, Butler WE, Carter BS, Chapman P, Stapleton CJ, Patel AB, Rodesch G, Smajda S, Berenstein A, Barak T, Erson-Omay EZ, Zhao H, Moreno-De-Luca A, Proctor MR, Smith ER, Orbach DB, Alper SL, Nicoli S, Boggon TJ, Lifton RP, Gunel M, King PD&, **Jin SC&**, Kahle KT&. [Mutation of key signaling regulators of cerebrovascular development in vein of Galen malformations](https://www.nature.com/articles/s41467-023-43062-z). ***Nature Communications***. #Equal contribution; &Corresponding author

80 Singh AK, Garrett Allington, Viviano S, McGee S, Kiziltug E, Ma S, **Zhao S**, Mekbib KY, Shohfi JP, Duy PQ, DeSpenza Jr T, Furey CG, Reeves BC, Smith H, Sousa AM, Cherskov A, Allocco A, Nelson-Williams C, Haider S, Rizvi SRA, Alper SL, Sestan N, Shimelis H, Walsh LK, Lifton RP, Moreno-De-Luca A, **Jin SC**, Kruszka P, Deniz E, Kahle KT. [A novel SMARCC1 BAFopathy implicates neural progenitor epigenetic dysregulation in human hydrocephalus](https://academic.oup.com/brain/advance-article-abstract/doi/10.1093/brain/awad405/7490822?redirectedFrom=fulltext&login=false) ***Brain***.

79 Greenberg ABW, Mehta N, Allington G, **Jin SC**, Moreno-De-Luca A, Kahle KT. [Molecular diagnostic yield of exome sequencing in patients with congenital hydrocephalus: a systematic review and meta-analysis](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2812266). ***JAMA Network Open***.

78 Mekbib KY, Muñoz W, Allington G, McGee S, Mehta NH, Shofi JP, Fortes C, Le HT, Nelson-Williams C, Nanda P, Dennis E, Kundishora AJ, Khanna A, Smith H, Ocken J, Greenberg ABW, Wu R, Moreno-De-Luca A, DeSpenza T Jr, Zhao S, Marlier A, **Jin SC**, Alper SL, Butler WE, Kahle KT. [Human genetics and molecular genomics of Chiari malformation type 1](https://www.cell.com/trends/molecular-medicine/fulltext/S1471-4914(23)00215-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1471491423002150%3Fshowall%3Dtrue). ***Trends in Molecular Medicine***. 

77 Almousa H, Lewis SA, Bakhtiari S, Nordlie SH, Pagnozzi A, Magee H, Efthymiou S, Heim JA, Cornejo P, Zaki MS, Anwar N, Maqbool S, Rahman F, Neilson DE, Vemuri A, **Jin SC**, Yang XR, Heidari A, van Gassen K, Trimouille A, Thauvin-Robinet C, Liu J, Bruel AL, Tomoum H, Shata MO, Hashem MO, Toosi MB, Ghayoor Karimiani E, Yeşil G, Lingappa L, Baruah D, Ebrahimzadeh F, Van-Gils J, Faivre L, Zamani M, Galehdari H, Sadeghian S, Shariati G, Mohammad R, van der Smagt J, Qari A, Vincent JB, Innes AM, Dursun A, Özgül RK, Akar HT, Bilguvar K, Mignot C, Keren B, Raveli C, Burglen L, Afenjar A, Donker Kaat L, van Slegtenhorst M, Alkuraya F, Houlden H, Padilla-Lopez S, Maroofian R, Sacher M, Kruer MC. [TRAPPC6B biallelic variants cause a neurodevelopmental disorder with TRAPP II and trafficking disruptions](https://academic.oup.com/brain/advance-article/doi/10.1093/brain/awad301/7275018?login=true). ***Brain***.

76 Ahmad N, Fazeli W, Schließke S, Lesca G, Gokce-Samar Z, Mekbib KY, **Jin SC**, Burton J, Hoganson G, Petersen A, Gracie S, Granger L, Bartels, E, Oppermann H, Kundishora AJ, Till M, Milleret-Pignot C, Dangerfield S, Viskochil D, Anderson KJ, Palculict TB, Schnur RE, Wentzensen IM, Tiller GE, Kahle KT, Kunz WS, Burkart S, Simons M, Sticht H, Jamra RA, Neuser S. [De novo variants in RAB11B cause various degrees of global developmental delay and intellectual disability in children](https://www.sciencedirect.com/science/article/abs/pii/S0887899423002813). ***Pediatric Neurology***.

75 Pinard A, Ye W, Fraser SM, Rosenfeld JA, Pichurin P, Hickey SE, Guo D, Cecchi AC, Guey S, Aloui C, Lee K, Kraemer M, Alyemni SO, University of Washington Center for Mendelian Genomics, Bamshad MJ, Nickerson DA, Tournier-Lasserve E, Haider S, **Jin SC**, Smith ER, Kahle KT, Jan LY, He M, Boerio ML, Milewicz DM. [Rare variants in ANO1, encoding a Calcium-activated chloride channel, predispose to Moyamoya disease](https://academic.oup.com/brain/advance-article-abstract/doi/10.1093/brain/awad172/7186631?login=false). ***Brain***.  

74 Timberlake AT, McGee S, Allington G, Kiziltug E, Wolfe EM, Stiegler AL, Boggon TJ, Sanyoura M, Morrow M, Wenger TL, Fernandes EM, Caluseriu O, Persing JA, **Jin SC**, Lifton RP, Kahle KT, Kruszka P. [De novo variants implicate chromatin modification, transcriptional regulation, and retinoic acid signaling in syndromic craniosynostosis](https://www.sciencedirect.com/science/article/pii/S0002929723001015). ***American Journal of Human Genetics***.

73 Mishra-Gorur K, Barak T, Kaulen L, Henegariu O, **Jin SC**, Aguilera SM, Goles G, Yalbir E, Nishimura S, Miyagishima D, Djenoune L, Altinok S, Rai DK, Viviano S, Prendergast A, Zerillo C, Ozcan K, Baran B, Sencar L, Goc N, Yarman Y, Ercan-Sencicek AG, Bilguvar K, Lifton RP, Moliterno J, Louvi A, Yuan S, Deniz E, Brueckner B, Gunel M. [Pleiotropic role of TRAF7 in skull-base meningiomas and congenital heart disease](https://www.pnas.org/doi/10.1073/pnas.2214997120). ***PNAS***.

72 Kundishora AJ#, Allington G#, McGee S#, Mekbib KY#, Gainullin V, Timberlake AT, Nelson-Williams C, Kiziltug E, Smith H, Ocken J, Shohfi J, Allocco AA, Duy PQ, Elsamadicy A, Dong W, **Zhao S**, **Wang Y-C**, Qureshi H, Diluna ML, Mane S, Tikhonova IR, **Fu P-Y**, Castaldi C, López-Giráldez F, Knight JR, Furey CG, Carter BS, Haider S, Moreno-De-Luca A, Alper SL, Gunel M, Millan F, Lifton RP, Torene RI#, **Jin SC#**, Kahle KT#&. [Multi-omic analyses implicate a neurodevelopmental program in the pathogenesis of cerebral arachnoid cysts](https://www.nature.com/articles/s41591-023-02238-2). ***Nature Medicine***. #Equal contribution;  &Corresponding author

### 2022

71 Duy PQ, Rakic P, Alper SL, Robert SM, Kundishora AJ, Butler WE, Walsh CA, Sestan N, Geschwind DH, **Jin SC**, Kahle KT. [A neural stem cell paradigm of pediatric hydrocephalus](https://academic.oup.com/cercor/advance-article/doi/10.1093/cercor/bhac341/6696466?searchresult=1). ***Cerebral Cortex***.

70 Timberlake AT, Kiziltug E, **Jin SC**, Nelson-Williams C, Loring E, Yale Center for Genome Analysis, Allocco AA, Marlier A, Banka S, Stuart H, Passos-Buenos MR, Rosa R, Rogatto SR, Tonne E, Stiegler AL, Boggon TJ, Alperovich M, Steinbacher D, Flores RL, Persing JA, Kahle KT, Lifton RP. [De novo mutations in the BMP signaling pathway in lambdoid craniosynostosis](https://link.springer.com/article/10.1007/s00439-022-02477-2). ***Human Genetics***.

69 Qureshi HQ#, Mekbib KY#, Allington G#, Elsamadicy AA, Duy PQ, Kundishora AJ, **Jin SC**, Kahle KT. [Familial and syndromic forms of arachnoid cyst implicate genetic factors in disease pathogenesis](https://academic.oup.com/cercor/advance-article/doi/10.1093/cercor/bhac257/6645819?login=true). ***Cerebral Cortex***.  

68 Guo H, Hou L, Shi Y, **Jin SC**, Zeng X, Li B, Lifton RP, Brueckner M, Zhao H, Lu Q. [Quantifying concordant genetic effects of de novo mutations on multiple disorders](https://elifesciences.org/articles/75551). ***eLife***.

67 Xie Y, Jiang W, Li H, **Jin SC**, Brueckner M, Zhao H. [Network assisted analysis of de novo variants using protein-protein interaction information identified 46
candidate genes for congenital heart disease](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010252). ***PLoS Genetics***. 

66 Dong W#, Wong KHY#, Liu Y#, Levy-Sakin M#, Hung W-C#, Li M, Li B, **Jin SC**, Choi J, Lopez-Giraldez F, Vaka D, Poon A, Chu C, Lao R, Balamir M, Movsesyan I, Malloy MJ, Zhao H, Kwok P-Y, Kane JP, Lifton RP, Pullinger CR. [Whole exome sequencing reveals damaging gene variants associated with hypoalphalipoproteinemia](https://www.jlr.org/article/S0022-2275(22)00042-6/fulltext). ***Journal of Lipid Research***. #Co-first authors.

65 Calame DG#, Herman I#, Marshall AE, Maroofian R, Donis KC, Fatih JM, Mitani T, Du H, Grochowski CM, Sousa S, Bakhtiari S, Io YA, Rocca C, Hunter JV, Sutton VR, Emrick LT, Boycott KM, Lossos A, Fellig Y, Prus E, Kalish Y, Meiner V, Suerink M, Ruivenkamp T, Muirhead K, Saadi NW, Zaki MS, Bouman A, Barakat TS, Skidmore DL, Osmond M, Silva TO, Houlden H, Murphy D, Karimiani EG, Jamshidi Y, Jaddoa AG, Tajsharghi H, **Jin SC**, Abbaszadegan MR, Ebrahimzadeh-Vesal R, Hosseini S, Alavi S, Bahreini A, Zarean E, Salehi MM, Robson S, Coban-Akdemir Z, Travaglini L, Nicita F, Jhangiani SN, Gibbs RA, Posey JE, Kruer MC, Kernohan KD, Saute JAM, Vanderver A, Pehlivan D, Marafi D, Lupski JR. [Biallelic variants in the ectonucleotidase ENTPD1 cause a complex neurodevelopmental disorder with intellectual disability, distinct white matter abnormalities, and spastic paraplegia](https://onlinelibrary.wiley.com/doi/10.1002/ana.26381). ***Annals of Neurology***. #Co-first authors.  

64 Dong W#, Kaymakcalan H#, **Jin SC#**, Diab NS#, Tanıdır C, Yalcin ASY, Ercan-Sencicek AG, Mane S, Gunel M, Lifton RP, Bilguvar K, Brueckner M. [Mutation spectrum of congenital heart disease in a consanguineous Turkish population](https://onlinelibrary.wiley.com/doi/full/10.1002/mgg3.1944). ***Molecular Genetics & Genomic Medicine***. #Co-first authors. 

63 **Wang Y-C#**, Wu Y#, **Choi J#**, Allington G#, **Zhao S#**, **Khanfar M#**, **Yang K#**, **Fu P-Y**, **Wrubel M**, **Yu X**, Mekbib KY, Ocken J, Smith H, Shohfi J, Kahle KT, Lu Q&, **Jin SC&**. [Computational genomics in the era of precision medicine: applications to variant analysis and gene therapy](https://www.mdpi.com/2075-4426/12/2/175). ***Journal of Personalized Medicine***. #Co-first authors; &Co-corresponding authors. [**Feature paper**]

62 Duy PQ#, Weise SC#, Marini C, Li X, Liang D, Dahl P, Ma S, Spajic A, Dong W, Juusola J, Kiziltug E, Kundishora AJ, Koundal S, Pedram MZ, Torres-Fernández LZ, Händler K, Domenico ED, Becker M, Ulas T, Juranek SA, Cuevas E, Hao LT, Jux B, Sousa AM, Kim S-K, Li M, Yang Y, Takeo Y, Duque A, Nelson-Williams C, Ha Y, Selvaganesan K, Robert SM, Singh AK, Allington G, Furey CG, Timberlake AT, Reeves BC, Smith H, Dunbar A, DeSpenza Jr. T, Goto J, Marlier A, Moreno-De-Luc A, Yu X, Butler WE, Carter BS, Lake EM, Constable RT, Rakic P, Lin H, Deniz E, Benveniste H, Malvankar N, Estrada-Veras JI, Walsh CA, Alper SL, Schultze J, Paeschke K, Doetzlhofer A, Wulczyn FG, **Jin SC**, Lifton RP, Sestan N, Kolanus W, Kahle KT. [Impaired neurogenesis alters brain biomechanics in a neuroprogenitor-based genetic subtype of congenital hydrocephalus](https://www.nature.com/articles/s41593-022-01043-3). ***Nature Neuroscience***. #Co-first authors.  

61 Duy PQ, Rakic P, Alper SL, Butler WE, Walsh CA, Sestan N, Geschwind DH, **Jin SC**, Kahle KT. [Brain ventricles as windows into the development of the human cerebral cortex](https://www.sciencedirect.com/science/article/pii/S0896627321010175?dgcid=coauthor). ***Neuron***.

### 2021

60 Zech M#, Kopajtich R#, Steinbrücker K#, Bris C, Gueguen N, Feichtinger R, Achleitner M, Duzkale N, Périvier M, Koch J, Engelhardt H, Freisinger P, Wagner M, Brunet T, Berutti R, Smirnov D, Rodenburg RJ, Pais LS, Austin-Tse C, O’Leary M, Boesch S, Jech R, Bakhtiari S, **Jin SC**, Wilbert F, Kruer MC, Wortmann SB, Eckenweiler M, Mayr JA, Distelmaier F, Steinfeld R, Winkelmann J&, Prokisch H&. [Variants in mitochondrial ATP synthase cause variable neurologic phenotypes](https://onlinelibrary.wiley.com/doi/abs/10.1002/ana.26293). ***Annals of Neurology***. #Co-first authors; &Co-corresponding authors.

59 Tang CSM#, Mononen M#, Lam W-Y, **Jin SC**, Zhuang X, Garcia-Barcelo M-M, Lin Q, Yang Y, Sahara M, Eroglu E, Chien K&, Hong H&, Tma PKH&, Gruber P&. [Sequencing of a Chinese Tetralogy of Fallot cohort reveals clustering mutations in myogenic heart progenitors](https://insight.jci.org/articles/view/152198). ***JCI Insight***. #Co-first authors; &Co-corresponding authors.

58 Fazeli W, Bamborschke D, Moawia A, Bakhtiari S, Tafakhori A, Giersdorf M, Hahn A, Weik A, Kolzter K, Shafiee S, **Jin SC**, Körber F, Lee-Kirsch MA, Cirak S, Darvish H, Kruer MC, Koy A. [The phenotypic spectrum of PCDH12 associated disorders - five new cases and review of the literature](https://www.sciencedirect.com/science/article/pii/S1090379821001938). ***European Journal of Paediatric Neurology***.

57 DeSpenza Jr T#, Carlson M#, Panchagnula S, Robert S, Duy PQ, Mermin-Bunnell N, Reeves BC, Kundishora AJ, Elsamadicy AA, Smith H, Ocken J, Alper SL, **Jin SC**, Hoffman EJ&, Kahle KT&. [PTEN mutations in autism spectrum disorder and congenital hydrocephalus: developmental pleiotropy and therapeutic targets](https://www.sciencedirect.com/science/article/pii/S0166223621001661?dgcid=coauthor). ***Trends in Neurosciences***. #Co-first authors; &Co-corresponding authors. 
 
56 Zech M, Kumar KR, Reining S, Reunert J, Tchan M, Riley LG, Drew AP, Adam RJ, Berutti R, Biskup S, Derive N, Bakhtiari S, **Jin SC**, Kruer MC, Bardakjian T, Gonzales-Aalegre P, Sarmiento IJK, Mencacci NE, Lubbe SJ, Kurian MA, Cclot F, Menereett A, de Sainte Agathe J-M, Fung VSC, Vidailhet M, Baumann M, Marquardt T, Winkelmann J, Boesch S. [Biallelic AOPEP loss-of-function variants linked to progressive dystonia with prominent limb involvement](https://movementdisorders.onlinelibrary.wiley.com/doi/10.1002/mds.28804). ***Movement Disorders***.  

55 Allington G, Duy PQ, **Ryou J**, Singh A, Kiziltug E, Robert SM, Kundishora A, **King S**, Haider S, Kahle KT, **Jin SC**. [Genomic approaches to improve the clinical diagnosis and management of congenital hydrocephalus patients](https://thejns.org/pediatrics/view/journals/j-neurosurg-pediatr/aop/article-10.3171-2021.8.PEDS21368/article-10.3171-2021.8.PEDS21368.xml)  ***Journal of Neurosurgery:Pediatrics***.

54 Barak T#, Ristori E#, Ercan-Sencicek AG, Miyagishima DF, Nelson-Williams C, Dong W, **Jin SC**, Prendergast A, Henegariu O, Erson-Omay EZ, Harmancı AS, Guy M, Gültekin B, Kilic D, Rai DK, Goc N, Aguilera SM, Gülez B, Altinok S, Ozcan K, Yarman Y, Coskun S, Sempou E, Deniz E, Hintzen J, Cox A, Fomchenko E, Jung SW, Ozturk AK, Louvi A, Bilgüvar K, Connolly Jr. ES, Khokha MK, Kahle KT, Yasuno K, Lifton RP, Mishra-Gorur K&, Nicoli S&, Günel M&. [PPIL4 is essential for brain angiogenesis and implicated in intracranial aneurysm in humans](https://www.nature.com/articles/s41591-021-01572-7). ***Nature Medicine***. #Co-first authors; &Co-corresponding authors.

53 Richard EM#, Bakhtiari S#, Marsh APL#, Kaiyrzhanov R#, Wagner M#, Shetty S, Pagnozzi A, Nordlie SM, Guida BS, Cornejo P, Magee H, Liu J, Norton BY, Webster RI, Worgan L, Hakonarson H, Li J, Guo Y, Jain M, Blesson A, Rodan LH, Abbott M, Comi A, Cohen JS, Alhaddad B, Meitinger T, Lenz D, Ziegler A, Kotzaeridou U, Brunet T, Chassevent A, Smith-Hicks C, Smith-Hicks J, Weiden T, Hahn A, Zharkinbekova N, Turnpenny P, Tucci A, Yelton M, Horvath R, Gungor S, Hiz S, Oktay Y, Lochmuller H, Zollino M, Morleo M, Marangi G, Nigro V, Torella A, Pinelli M, Amenta S, TUDP Study Group, Husain RA, Grossmann B, Rapp M, Steen C, Marquardt I, Grimmel M, Grasshoff U, Korenke GC, Owczarek-Lipska M, Neidhardt J, Radio FC, Mancini C, Sepulveda DJC, McWalter K, Begtrup A, Crunk A, Guillen Sacoto MJ, Person R, Schnur RE, Mancardi MM, Kreuder F, Striano P, Zara F, Chung WK, Marks WA, Tartaglia M, Striano V, Christodoulou J, Kaslin J, Padilla-Lopez S, Bilguvar K, Munchau A, Ahmed ZM, Hufnagel RB, Fahey MC, Maroofian R, Houlden H, Sticht H, Mane SM, Rad A, Vona B, **Jin SC**, Haack TB, Makowski C, Hirsch Y, Riazuddin S&, Kruer MC&. [Biallelic variants in SPATA5L1 lead to intellectual disability, spastic-dystonic cerebral palsy, epilepsy and hearing loss](https://www.sciencedirect.com/science/article/pii/S0002929721003025?dgcid=coauthor). ***American Journal of Human Genetics***. #Co-first author; &Co-corresponding authors.    

52 Calame DG#, Bakhtiari S#, Logan R, Coban-Akdemir Z, Du H, Mitani T, Fatih JM, Hunter JV, Herman I, Pehlivan D, Jhangiani SN, Person R, Schnur RE, **Jin SC**, Bilguvar K, Posey JE, Koh S, Firouzabadi SG, Alehabib E, Tafakhori A, Esmkhani S, Gibbs RA, Noureldeen MM, Zaki MS, Marafi D, Darvish H&, Kruer MC&, Lupski JR&. [Biallelic loss-of-function variants in the splicing regulator NSRP1 cause a severe neurodevelopmental disorder with spastic cerebral palsy and epilepsy](https://www.nature.com/articles/s41436-021-01291-x). ***Genetics in Medicine***. #Co-first authors; &Co-corresponding authors. 

51 Diab NS#, Barish S#, Dong W#, **Zhao S#**, Allington G, **Yu X**, Kahle KT, Brueckner M&, **Jin SC&**. [Molecular genetics and complex inheritance of congenital heart disease](https://www.mdpi.com/2073-4425/12/7/1020). ***Genes***. #Co-first authors; &Co-corresponding authors. [**Cover story**](https://www.mdpi.com/2073-4425/12/7?utm_campaign=releaseissue_genesutm_medium=emailutm_source=releaseissueutm_term=coverlink).

50 Kundishora AJ, Singh AK, Allington G, Dunbar AM, Duy PQ, **Ryou J**, Alper SL, **Jin SC**, Kahle KT. [Genomics of human congenital hydrocephalus](https://link.springer.com/article/10.1007/s00381-021-05230-8). ***Child's Nervous System***. 

49 Lewis SA, Bakhtiari S, Heim J, Liu J, Huaang AJ, Musmacker A, **Jin SC**, Bilguvar K, Padilla-Lopez S, Kruer MC. [Mutation in ZDHHC15 leads to hypotonic cerebral palsy, autism, epilepsy, and intellectual disability](https://ng.neurology.org/content/7/4/e602). ***Neurology: Genetics***.

48 Omar S, **Jin SC**, Koumangoye R, Robert SM, Duran D, Nelson-Williams C, Huttner A, DiLuna M, Kahle KT, Delpire E. [Protein kinase D1 mutation associated with human epilepsy and peripheral nerve hypermyelination](https://onlinelibrary.wiley.com/doi/abs/10.1111/cge.13973). ***Clinical Genetics***.

47 Kundishora AJ#, **Peters ST#**, Pinard A, Duran D, Panchagnula S, Barak T, Miyagishima DF, Dong W, Smith H, Ocken J, Dunbar A, Nelson-Williams C, Haider S, Walker RL, Li B, Zhao H, Thumkeo D, Marlier A, Duy PQ, Diab NS, Reeves BC, Robert SM, Sujijantarat N, Stratman AN, Chen Y-H, **Zhao S**, Roszko I, Lu Q, Zhang B, Mane S, Castaldi C, López-Giráldez F, Knight JR, Bamshad MJ, Nickerson DA, Geschwind DH, Lang Chen S-S, Storm PB, Diluna ML, Matouk C, Orbach DB, Alper SL, Smith ER, Lifton RP, Gunel M, Milewicz DM, **Jin SC&**, Kahle KT&. [DIAPH1 mutations in non-East Asian patients with sporadic moyamoya disease](https://jamanetwork.com/journals/jamaneurology/fullarticle/2781029). ***JAMA Neurology***. #Co-first authors; &Co-corresponding authors.

46 Li M, Zeng X, Jin L, **Jin SC**, Dong W, Brueckner M, Lifton RP, Lu Q, Zhao H. [Integrative modeling of transmitted and de novo variants identifies novel risk genes for congenital heart disease](https://journal.hep.com.cn/qb/EN/10.15302/J-QB-021-0248). ***Quantitative Biology***.

45 Alsharhan H, He M, Edmondson AC, Chen J, Donald T, Bakhtiari S, Amor D, Jones EA, Vassallo G, Vincent G, Cogné B, Deb W, Werners AH, **Jin SC**, Bilguvar K, Christodoulou J, Webster RI, Yearwood KR, Ng BG, Freeze HN, Kruer MC, Li D, Raymond KM, Bhoj EJ, Sobering AK. [ALG13 X-linked intellectual disability: new variants, Glycosylation analysis, and expansion of the phenotype](https://onlinelibrary.wiley.com/doi/10.1002/jimd.12378). ***Journal of Inherited Metabolic Disease***.

44 Dzinovic I, Skorvanek M, Pavelekova P, Zhao C, Keren B, Whalen S, Bakhtiari S, **Jin SC**, Kruer MC, Jech R, Winkelmann J, Zech M. [Variant recurrence confirms the existence of a FBXO31-related spastic-dystonic cerebral palsy syndrome](https://onlinelibrary.wiley.com/doi/epdf/10.1002/acn3.51335). ***Annals of Clinical and Translational Neurology***.

43 Diab NS#, **King S#**, Dong W#, Allington G, Sheth A, **Peters S**, Kahle KT&, **Jin SC&**. [Analysis workflow to assess de novo genetic variants from whole-exome sequencing](https://star-protocols.cell.com/protocols/514?fbclid=IwAR0RAxAiY1LbdBXWdlWDL_fcfKIx7gzABfPn4F8tEs_VobHYDdmWO2iqJKY). ***STAR Protocols***. #Co-first authors; &Co-corresponding authors. 

42 Bakhtiari S, Tafakhori A, **Jin SC**, Guida BS, Alehabib E, Firouzbadi S, Bilguvar K, Darvish H, Kruer MC. [Recessive COL4A2 mutation leads to intellectual disability, epilepsy, and spastic cerebral palsy](https://ng.neurology.org/content/7/3/e583). ***Neurology: Genetics***.

41 Lewis SA, Shetty S, Wilson B, Huang AJ, **Jin SC**, Smithers-Sheedy H, Fahey MC, Kruer MC. [Insights from genetic studies of cerebral palsy](https://www.frontiersin.org/articles/10.3389/fneur.2020.625428/full). ***Frontiers in Neurology***.

40 Wiessner M, Maroofian R, Ni M-Y, Bartesaghi L, Pedroni A, Müller JS, Stucka R, Beetz C, Efthymiou S, Santorelli FM, Alfares AA, Zhu C, Meszarosova AU, Alehabib E, Bakhtiari S, Jannecke AR, Otero MG, Chen JY, Peterson JT, Skraban C, Goldstein A, Strom TM, Jonghe PD, Deconinck T, Ridder WD, Winter JD, Pasquariello R, Ricca I, Alfadhel M, van de Warrenburg BP, Portier R, Bergmann C, Firouzabadi SG, **Jin SC**, Bilguvar K, ..., Senderek J. [Biallelic variants in HPDL cause pure and complicated hereditary spastic paraplegia](https://academic.oup.com/brain/advance-article/doi/10.1093/brain/awab041/6273093?rss=1).  ***Brain***. 

### 2020

39 **Jin SC#**, Dong W#, Kundishora AJ#, Panchagnula S#, Moreno-De-Luca A#, Furey CG, Allocco AA, Walker RL, Nelson-Williams C, Smith H, Dunbar A, Conine S, Lu Q, Zeng X, Sierant MC, Knight JR, Sullivan W, Duy PQ, DeSpenza T, Reeves BC, Karimy JK, Marlier A, Castaldi C, Tikhonova IR, Li B, Peña HP, Broach JR, Kabachelor EM, Ssenyonga P, Hehnly C, Ge L, Keren B, Timberlake AT, Goto J, Mangano FT, Johnston JM, Butler WE, Warf BC, Smith ER, Schiff SJ, Limbrick DD, Heuer G, Jackson EM, Iskandar BJ, Mane S, Haider S, Guclu B, Bayri Y, Sahin Y, Duncan CC, Apuzzo ML, DiLuna ML, Hoffman EJ, Sestan N, Ment LR, Alper SL, Bilguvar K, Geschwind DH, Günel M, Lifton RP, Kahle KT. [Exome sequencing implicates genetic disruption of prenatal neuro-gliogenesis in sporadic congenital hydrocephalus](https://www.nature.com/articles/s41591-020-1090-2). ***Nature Medicine***. #Co-first authors .\
**Press coverage:** [Nature Medicine](https://www.nature.com/articles/s41591-020-1120-0), [Faculty Opinions](https://facultyopinions.com/prime/738854794), [Yale News](https://medicine.yale.edu/news-article/28466/)

38 **Jin SC#**, Lewis S#, Bakhtiari S#, Zeng X#, Sierant MC, Shetty S, Nordlie S, Elie A, Corbett M, Norton B, van Eyk C, Haider S, Guida B, Magee H, Liu J, Pastore S, Vincent J, Brunstrom-Hernandez J, Papavasileiou A, Fahey M, Berry J, Harper K, Zhou C, Zhang J, Li B, Zhao H, Heim J, Webber D, Frank M, Xia L, Xu Y, Zhu D, Zhang B, Sheth A, Knight JR, Castaldi C, Tikhonoa I, Lopez-Giraldez F, Keren B, Whalen S, Buratti J, Doummar D, Cho M, Retterer K, Millan F, Wang Y, Waugh J, Rodan L, Cohen J, Fatemi A, Lin A, Phillips J, Feyma T, MacLennan S, Vaughan S, Crompton K, Reid S, Reddihough D, Shang Q, Gao C, Novak I, Badawi N, Wilson Y, McIntyre S, Mane S, Wang X, Amor D, Zarnescu D, Lu Q, Xing Q†, Zhu C†, Bilguvar K, Padilla-Lopez S, Lifton RP, Gecz J, MacLennan A, Kruer MC. [Mutations disrupting neuritogenesis genes confer risk for cerebral palsy](https://www.nature.com/articles/s41588-020-0695-1). ***Nature Genetics***. #Co-first authors .\
**Press coverage:** [NIH](https://www.nih.gov/news-events/news-releases/about-14-cerebral-palsy-cases-may-be-tied-brain-wiring-genes), [WashU News](https://medicine.wustl.edu/news/cerebral-palsy-also-has-genetic-underpinnings/), [AJMG News](https://onlinelibrary.wiley.com/doi/epdf/10.1002/ajmg.a.61646)

37 Dong W#, **Jin SC#**, Allocco A#, Zeng X#, Sheth A, Panchagnula S, Castonguay A, Lorenzo L, Islam B, Brindle G, Bachand K, Hu J, Sularz A, Gaillard J, Choi J, Dunbar A, Nelson-Williams C, Kiziltug E, Furey C, Conine S, Duy P, Kundishora AJ, Loring E, Li B, Lu Q, Zhou G, Liu W, Li X, Sierant MC, Mane S, Castaldi C, Lopez-Giraldez F, Knight JR, Sekula R, Simard M, Eskandar E, Gottschalk C, Moliterno J, Gunel M, Gerrard J, Dib-Hajj S, Waxman S, Barker F, Alper S, Chahine M, Haider S, De Koninck Y, Lifton RP, Kahle KT. [Exome sequencing implicates impaired GABA signaling and neuronal ion transport in trigeminal neuralgia](https://www.sciencedirect.com/science/article/pii/S2589004220307446). ***iScience***. #Co-first authors 

36 Morton SU, Shimamura A, Newburger PE, Opotowsky AR, Quiat D, Pereira AC, **Jin SC**, Gurvitz M, Brueckner M, Chung WK, Shen Y, Bernstein D, Gelb BD, Giardini A, Goldmuntz E, Kim RW, Lifton RP, Porter GA, Srivastava D, Tristani-Firouzi M, Newburger JW, Seidman JG, Seidman CE. [Damaging variants in genes associated with increased cancer risk among congenital heart disease patients](https://jamanetwork.com/journals/jamacardiology/fullarticle/2772083?guestAccessKey=8f7539c8-dd74-4220-bfe2-5eeb72d2fd75&utm_source=fbpage&utm_medium=social_jamacard&utm_term=3961651915&utm_campaign=article_alert&linkId=102524490&fbclid=IwAR0wn_cKe5ijO2l_0hjUdYUjrJ7xgCKdxsHut_dbGsaQg5viFiqfLNfZbJ0). ***JAMA Cardiology***.

35 Sullivan W, Reeves BC, Duy PQ, Nelson-Williams C, Dong W, **Jin SC**, Kahle KT. [Exome sequencing as a potential diagnostic adjunct in sporadic congenital hydrocephalus](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2772999). ***JAMA Pediatrics***.

### Peter's work pre-dating the lab:

34 Wagner M, Lévy J, Jung-Klawitter S, Bakhtiari S, Monteiro F, Maroofian R, Bierhals T, Hempel M, Elmaleh M, Kitajima JP, Kim CA, Salomao JG, Amor DJ, Cooper MS, Perrin L, Pipiras E, Neu A, Doosti M, Karimiani EG, Toosi MB, Houlden H, **Jin SC**, Si Y, Rodan LH, Venselaar H, Kruer M, Kok F, Hoffmann GF, Strom TM, Wortmann SB, Tabet A-C, Opladen T. [Loss of TNR causes a non-progressive neurodevelopmental disorder with spasticity and transient opisthotonus](https://www.nature.com/articles/s41436-020-0768-7). ***Genetics in Medicine***. 

### 2019

33 Allocco AA#, **Jin SC#**, Duy PQ#, Furey CG, Zeng X, Dong W, Nelson-Williams C, Karimy JK, DeSpenza T, Hao LT, Reeves B, Haider S, Gunel M, Lifton RP, Kahle KT. [Recessive inheritance of congenital hydrocephalus with other structural brain abnormalities caused by compound heterozygous mutations in ATP1A3. Frontiers Cellular Neuroscience](https://www.frontiersin.org/articles/10.3389/fncel.2019.00425/full). ***Frontiers in Cellular Neuroscience***. #Co-first authors

32 **Jin SC#**, Furey CG#, Zeng X, Allocco A, Nelson-Williams C, Dong W, Karimy JK, Wang K, Ma S, Delpire E, Kahle KT. [SLC12A ion transporter mutations in sporadic and familial human congenital hydrocephalus](https://onlinelibrary.wiley.com/doi/full/10.1002/mgg3.892). ***Molecular Genetics & Genomic Medicine***. #Co-first authors

31 Timberlake AT, **Jin SC**, Nelson-Williams C, Wu R, Furey CG, Islam B, Haider S, Loring E, Galm A; Yale Center for Genome Analysis, Steinbacher DM, Larysz D, Staffenberg DA, Flores RL, Rodriguez ED, Boggon TJ, Persing JA, Lifton RP. [Mutations in TFAP2B and previously unimplicated genes of the BMP, Wnt, and Hedgehog pathways in syndromic craniosynostosis](https://www.pnas.org/content/116/30/15116.long). ***PNAS***. 

30 Robson A, Makova SZ, Barish S, Zaidi S, Mehta S, Drozd J, **Jin SC**, Gelb BD, Seidman CE, Chung WK, Lifton RP, Khokha MK, Brueckner M. [Histone H2B monoubiquitination regulates heart development via epigenetic control of cilia motility](https://www.pnas.org/content/116/28/14049.long). ***PNAS***.

29 Chang SJ, **Jin SC**, Jiao X, Galán JE.[Unique features in the intracellular transport of typhoid toxin revealed by a genome-wide screen](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1007704). ***PLoS Pathogens***. 

28 Helbig KL, Lauerer RJ, Bahr JC, Souza IA, Myers CT, Uysal B, Schwarz N, Gandini MA, Huang S, Keren B, Mignot C, Afenjar A, Billette de Villemeur T, Héron D, Nava C, Valence S, Buratti J, Fagerberg CR, Soerensen KP, Kibaek M, Kamsteeg EJ, Koolen DA, Gunning B, Schelhaas HJ, Kruer MC, Fox J, Bakhtiari S, Jarrar R, Padilla-Lopez S, Lindstrom K, **Jin SC**, Zeng X, Bilguvar K, Papavasileiou A, Xing Q, Zhu C, Boysen K, Vairo F, Lanpher BC, Klee EW, Tillema JM, Payne ET, Cousin MA, Kruisselbrink TM, Wick MJ, Baker J, Haan E, Smith N, Sadeghpour A, Davis EE, Katsanis N; Task Force for Neonatal Genomics, Corbett MA, MacLennan AH, Gecz J, Biskup S, Goldmann E, Rodan LH, Kichula E, Segal E, Jackson KE, Asamoah A, Dimmock D, McCarrier J, Botto LD, Filloux F, Tvrdik T, Cascino GD, Klingerman S, Neumann C, Wang R, Jacobsen JC, Nolan MA, Snell RG, Lehnert K, Sadleir LG, Anderlid BM, Kvarnung M, Guerrini R, Friez MJ, Lyons MJ, Leonhard J, Kringlen G, Casas K, El Achkar CM, Smith LA, Rotenberg A, Poduri A, Sanchis-Juan A, Carss KJ, Rankin J, Zeman A, Raymond FL, Blyth M, Kerr B, Ruiz K, Urquhart J, Hughes I, Banka S; Deciphering Developmental Disorders Study, Hedrich UBS, Scheffer IE, Helbig I, Zamponi GW, Lerche H, Mefford HC. [De novo pathogenic variants in CACNA1E cause developmental and epileptic encephalopathy with contractures, macrocephaly, and dyskinesias](https://www.sciencedirect.com/science/article/pii/S0002929719300606?via%3Dihub). ***American Journal of Human Genetics***.

27 Zeng X, Hunt A, **Jin SC**, Duran D, Gaillard J, Kahle KT. [EphrinB2-EphB4-RASA1 signaling in human cerebrovascular development and disease](https://www.sciencedirect.com/science/article/pii/S1471491419300206?via%3Dihub). ***Trends in Molecular Medicine***. 

26 Duran D#, Zeng X#, **Jin SC#**, Choi J, Nelson-Williams C, Yatsula B, Gaillard J, Furey CG, Lu Q, Timberlake AT, Dong W, Sorscher MA, Loring E, Klein J, Allocco A, Hunt A, Conine S, Karimy JK, Youngblood MW, Zhang J, DiLuna ML, Matouk CC, Mane S, Tikhonova IR, Castaldi C, López-Giráldez F, Knight J, Haider S, Soban M, Alper SL, Komiyama M, Ducruet AF, Zabramski JM, Dardik A, Walcott BP, Stapleton CJ, Aagaard-Kienitz B, Rodesch G, Jackson E, Smith ER, Orbach DB, Berenstein A, Bilguvar K, Vikkula M, Gunel M, Lifton RP, Kahle KT. [Mutations in chromatin modifier and Ephrin signaling genes in Vein of Galen malformation](https://www.sciencedirect.com/science/article/pii/S089662731831050X?via%3Dihub). ***Neuron***. #Co-first authors .\
**Press coverage:** [Yale News](https://yaledailynews.com/blog/2019/01/15/study-identifies-mutation-for-rare-infant-brain-disease/)

### 2018

25 Furey CG, Zeng X, Dong W, **Jin SC**, Choi J, Timberlake AT, Dunbar AM, Allocco AA, Günel M, Lifton RP, Kahle KT. [Human Genetics and Molecular Mechanisms of Congenital Hydrocephalus](https://www.sciencedirect.com/science/article/abs/pii/S1878875018320618?via%3Dihub). ***World Neurosurgery***. 

24 Furey CG#, Choi J#, **Jin SC**, Zeng X, Timberlake AT, Nelson-Williams C, Mansuri MS, Lu Q, Duran D, Panchagnula S, Allocco A, Karimy JK, Khanna A, Gaillard JR, DeSpenza T, Antwi P, Loring E, Butler WE, Smith ER, Warf BC, Strahle JM, Limbrick DD, Storm PB, Heuer G, Jackson EM, Iskandar BJ, Johnston JM, Tikhonova I, Castaldi C, López-Giráldez F, Bjornson RD, Knight JR, Bilguvar K, Mane S, Alper SL, Haider S, Guclu B, Bayri Y, Sahin Y, Apuzzo MLJ, Duncan CC, DiLuna ML, Günel M, Lifton RP, Kahle KT. [De novo mutation in genes regulating neural stem cell fate in human congenital hydrocephalus](https://www.sciencedirect.com/science/article/pii/S0896627318304872?via%3Dihub). ***Neuron***. #Co-first authors

23 Fomchenko EI, Duran D, **Jin SC**, Dong W, Erson-Omay EZ, Antwi P, Allocco A, Gaillard JR, Huttner A, Gunel M, DiLuna ML, Kahle KT. [De novo MYH9 mutation in congenital scalp hemangioma](http://molecularcasestudies.cshlp.org/content/4/4/a002998.long). ***Cold Spring Harbor Molecular Case Studies***. 

22 Antwi P, Hong CS, Duran D, **Jin SC**, Dong W, DiLuna M, Kahle KT. [A novel association of campomelic dysplasia and hydrocephalus with an unbalanced chromosomal translocation upstream of SOX9](http://molecularcasestudies.cshlp.org/content/4/3/a002766.long). ***Cold Spring Harbor Molecular Case Studies***. 

21 Scholl UI, Stölting G, Schewe J, Thiel A, Tan H, Nelson-Williams C, Vichot AA, **Jin SC**, Loring E, Untiet V, Yoo T, Choi J, Xu S, Wu A, Kirchner M, Mertins P, Rump LC, Onder AM, Gamble C, McKenney D, Lash RW, Jones DP, Chune G, Gagliardi P, Choi M, Gordon R, Stowasser M, Fahlke C, Lifton RP. [CLCN2 chloride channel mutations in familial hyperaldosteronism type II](https://www.nature.com/articles/s41588-018-0048-5). ***Nature Genetics***. 

### 2017

20 **Jin SC#**, Homsy J#, Zaidi S#, Lu Q, Morton S, DePalma SR, Zeng X, Qi H, Chang W, Sierant MC, Hung WC, Haider S, Zhang J, Knight J, Bjornson RD, Castaldi C, Tikhonoa IR, Bilguvar K, Mane SM, Sanders SJ, Mital S, Russell MW, Gaynor JW, Deanfield J, Giardini A, Porter GA Jr, Srivastava D, Lo CW, Shen Y, Watkins WS, Yandell M, Yost HJ, Tristani-Firouzi M, Newburger JW, Roberts AE, Kim R, Zhao H, Kaltman JR, Goldmuntz E, Chung WK, Seidman JG, Gelb BD, Seidman CE, Lifton RP, Brueckner M. [Contribution of rare inherited and de novo variants in 2,871 congenital heart disease probands](https://www.nature.com/articles/ng.3970). ***Nature Genetics***. #Co-first authors. **[>700 cites]**

19 Huang KL, Marcora E, Pimenova AA, Di Narzo AF, Kapoor M, **Jin SC**, Harari O, Bertelsen S, Fairfax BP, Czajkowski J, Chouraki V, Grenier-Boley B, Bellenguez C, Deming Y, McKenzie A, Raj T, Renton AE, Budde J, Smith A, Fitzpatrick A, Bis JC, DeStefano A, Adams HHH, Ikram MA, van der Lee S, Del-Aguila JL, Fernandez MV, Ibañez L; International Genomics of Alzheimer's Project; Alzheimer's Disease Neuroimaging Initiative, Sims R, Escott-Price V, Mayeux R, Haines JL, Farrer LA, Pericak-Vance MA, Lambert JC, van Duijn C, Launer L, Seshadri S, Williams J, Amouyel P, Schellenberg GD, Zhang B, Borecki I, Kauwe JSK, Cruchaga C, Hao K, Goate AM. [A common haplotype lowers PU.1 expression in myeloid cells and delays onset of Alzheimer's disease](https://www.nature.com/articles/nn.4587). ***Nature Neuroscience***.

### 2016

18 Duran D#, **Jin SC#**, DeSpenza T Jr#, Nelson-Williams C, Cogal AG, Abrash EW, Harris PC, Lieske JC, Shimshak SJ, Mane S, Bilguvar K, DiLuna ML, Günel M, Lifton RP, Kahle KT. [Digenic mutations of human OCRL paralogs in Dent's disease type 2 associated with Chiari I malformation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5143364/). ***Human Genome Variation***. #Co-first authors

17 Song W, Hooli B, Mullin K, **Jin SC**, Cella M, Ulland TK, Wang Y, Tanzi RE, Colonna M. [Alzheimer's disease-associated TREM2 variants exhibit either decreased or increased ligand-dependent activation](https://www.sciencedirect.com/science/article/abs/pii/S1552526016302035?via%3Dihub). ***Alzheimer's & Dementia***. 

16 Benitez BA, Davis AA, **Jin SC**, Ibanez L, Ortega-Cubero S, Pastor P, Choi J, Cooper B, Perlmutter JS, Cruchaga C. [Resequencing analysis of five Mendelian genes and the top genes from genome-wide association studies in Parkinson's Disease](https://molecularneurodegeneration.biomedcentral.com/articles/10.1186/s13024-016-0097-0). ***Molecular Neurodegeneration***. 

### 2015

15 Homsy J, Zaidi S, Shen Y, Ware JS, Samocha KE, Karczewski KJ, DePalma SR, McKean D, Wakimoto H, Gorham J, **Jin SC**, Deanfield J, Giardini A, Porter GA Jr, Kim R, Bilguvar K, López-Giráldez F, Tikhonova I, Mane S, Romano-Adesman A, Qi H, Vardarajan B, Ma L, Daly M, Roberts AE, Russell MW, Mital S, Newburger JW, Gaynor JW, Breitbart RE, Iossifov I, Ronemus M, Sanders SJ, Kaltman JR, Seidman JG, Brueckner M, Gelb BD, Goldmuntz E, Lifton RP, Seidman CE, Chung WK. [De novo mutations in congenital heart disease with neurodevelopmental and other congenital anomalies](https://science.sciencemag.org/content/350/6265/1262.long). ***Science*** .

14 **Jin SC**, Benitez BA, Deming Y, Cruchaga C. [Pooled-DNA sequencing for elucidating new genomic risk factors, rare variants underlying Alzheimer's disease](https://link.springer.com/protocol/10.1007%2F978-1-4939-2627-5_18). ***Methods in Molecular Biology***.

13 **Jin SC**, Carrasquillo MM, Benitez BA, Skorupa T, Carrell D, Patel D, Lincoln S, Krishnan S, Kachadoorian M, Reitz C, Mayeux R, Wingo TS, Lah JJ, Levey AI, Murrell J, Hendrie H, Foroud T, Graff-Radford NR, Goate AM, Cruchaga C, Ertekin-Taner N. [TREM2 is associated with increased risk for Alzheimer's disease in African Americans](https://molecularneurodegeneration.biomedcentral.com/articles/10.1186/s13024-015-0016-9). ***Molecular Neurodegeneration***. **[>140 cites]**

### 2014

12 **Jin SC**, Benitez BA, Karch CM, Cooper B, Skorupa T, Carrell D, Norton JB, Hsu S, Harari O, Cai Y, Bertelsen S, Goate AM, Cruchaga C. [Coding variants in TREM2 increase risk for Alzheimer's disease](https://academic.oup.com/hmg/article/23/21/5838/2900998). ***Human Molecular Genetics***. **[>270 cites]**

11 Benitez BA#, **Jin SC#**, Guerreiro R, Graham R, Lord J, Harold D, Sims R, Lambert JC, Gibbs JR, Bras J, Sassi C, Harari O, Bertelsen S, Lupton MK, Powell J, Bellenguez C, Brown K, Medway C, Haddick PC, van der Brug MP, Bhangale T, Ortmann W, Behrens T, Mayeux R, Pericak-Vance MA, Farrer LA, Schellenberg GD, Haines JL, Turton J, Braae A, Barber I, Fagan AM, Holtzman DM, Morris JC; 3C Study Group; EADI consortium; Alzheimer's Disease Genetic Consortium (ADGC); Alzheimer's Disease Neuroimaging Initiative (ADNI); GERAD Consortium, Williams J, Kauwe JS, Amouyel P, Morgan K, Singleton A, Hardy J, Goate AM, Cruchaga C. [Missense variant in TREML2 protects against Alzheimer's disease](https://www.sciencedirect.com/science/article/pii/S0197458013006490?via%3Dihub). ***Neurobiology of Aging***. #Co-first authors.

10 Cruchaga C, Karch CM#, **Jin SC#**, Benitez BA, Cai Y, Guerreiro R, Harari O, Norton J, Budde J, Bertelsen S, Jeng AT, Cooper B, Skorupa T, Carrell D, Levitch D, Hsu S, Choi J, Ryten M, Sassi C, Bras J, Gibbs RJ, Hernandez DG, Lupton MK, Powell J, Forabosco P, Ridge PG, Corcoran CD, Tschanz JT, Norton MC, Munger RG, Schmutz C, Leary M, Demirci FY, Bamne MN, Wang X, Lopez OL, Ganguli M, Medway C, Turton J, Lord J, Braae A, Barber I, Brown K; Alzheimer's Research UK (ARUK) Consortium, Pastor P, Lorenzo-Betancor O, Brkanac Z, Scott E, Topol E, Morgan K, Rogaeva E, Singleton A, Hardy J, Kamboh MI, George-Hyslop PS, Cairns N, Morris JC, Kauwe JSK, Goate AM. [Rare coding variants in the phospholipase D3 gene confer risk for Alzheimer's disease](https://www.nature.com/articles/nature12825). ***Nature***. #Co-second authors. 

### 2013

9 Benitez BA, Karch CM, Cai Y, **Jin SC**, Cooper B, Carrell D, Bertelsen S, Chibnik L, Schneider JA, Bennett DA; Alzheimer's Disease Neuroimaging Initiative; Genetic and Environmental Risk for Alzheimer's Disease Consortium GERAD, Fagan AM, Holtzman D, Morris JC, Goate AM, Cruchaga C. [The PSEN1, p.E318G variant increases the risk of Alzheimer's disease in APOE-ε4 carriers](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1003685). ***PLoS Genetics***. 

8 Cruchaga C, Kauwe JS, Harari O, **Jin SC**, Cai Y, Karch CM, Benitez BA, Jeng AT, Skorupa T, Carrell D, Bertelsen S, Bailey M, McKean D, Shulman JM, De Jager PL, Chibnik L, Bennett DA, Arnold SE, Harold D, Sims R, Gerrish A, Williams J, Van Deerlin VM, Lee VM, Shaw LM, Trojanowski JQ, Haines JL, Mayeux R, Pericak-Vance MA, Farrer LA, Schellenberg GD, Peskind ER, Galasko D, Fagan AM, Holtzman DM, Morris JC; GERAD Consortium; Alzheimer’s Disease Neuroimaging Initiative (ADNI); Alzheimer Disease Genetic Consortium (ADGC), Goate AM. [GWAS of cerebrospinal fluid tau levels identifies risk variants for Alzheimer's disease](https://www.sciencedirect.com/science/article/pii/S0896627313001840?via%3Dihub). ***Neuron***.  

7 Benitez BA, Cooper B, Pastor P, **Jin SC**, Lorenzo E, Cervantes S, Cruchaga C. [TREM2 is associated with the risk of Alzheimer's disease in Spanish population](https://www.sciencedirect.com/science/article/pii/S0197458012006495?via%3Dihub). ***Neurobiology of Aging***.  

6 Patel PJ, Beaty TH, Ruczinski I, Murray JC, Marazita ML, Munger RG, Hetmanski JB, Wu T, Murray T, Rose M, Redett RJ, **Jin SC**, Lie RT, Su-Chou YH, Wang H, Ye X, Yeow V, Chong S, Jee SH, Shi B, Scott AF. [X-linked markers in the Duchenne muscular dystrophy gene associated with oral clefts](https://onlinelibrary.wiley.com/doi/full/10.1111/eos.12025). ***European Journal of Oral Sciences***. 

### 2012

5 **Jin SC**, Pastor P, Cooper B, Cervantes S, Benitez BA, Razquin C, Goate A; Ibero-American Alzheimer Disease Genetics Group Researchers, Cruchaga C. [Pooled-DNA sequencing identifies novel causative variants in PSEN1, GRN and MAPT in a clinical early-onset and familial Alzheimer's disease Ibero-American cohort](https://alzres.biomedcentral.com/articles/10.1186/alzrt137). ***Alzheimer's Research & Therapy***. 

4 Wang H, Zhang T, Wu T, Hetmanski JB, Ruczinski I, Schwender H, Liang KY, Murray T, Fallin MD, Redett RJ, Raymond GV, **Jin SC**, Chou YH, Chen PK, Yeow V, Chong SS, Cheah FS, Jee SH, Jabs EW, Scott AF, Beaty TH. [The FGF and FGFR Gene Family and Risk of Cleft Lip With or Without Cleft Palate](https://journals.sagepub.com/doi/full/10.1597/11-132?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%3dpubmed). ***The Cleft Palate-Craniofacial Journal***.

### 2011

3 Beaty TH, Ruczinski I, Murray JC, Marazita ML, Munger RG, Hetmanski JB, Murray T, Redett RJ, Fallin MD, Liang KY, Wu T, Patel PJ, **Jin SC**, Zhang TX, Schwender H, Wu-Chou YH, Chen PK, Chong SS, Cheah F, Yeow V, Ye X, Wang H, Huang S, Jabs EW, Shi B, Wilcox AJ, Lie RT, Jee SH, Christensen K, Doheny KF, Pugh EW, Ling H, Scott AF. [Evidence for gene-environment interaction in a genome wide study of nonsyndromic cleft palate](https://onlinelibrary.wiley.com/doi/full/10.1002/gepi.20595). ***Genetic Epidemiology***.

### 2010

2 Beaty TH, Murray JC, Marazita ML, Munger RG, Ruczinski I, Hetmanski JB, Liang KY, Wu T, Murray T, Fallin MD, Redett RA, Raymond G, Schwender H, **Jin SC**, Cooper ME, Dunnwald M, Mansilla MA, Leslie E, Bullard S, Lidral AC, Moreno LM, Menezes R, Vieira AR, Petrin A, Wilcox AJ, Lie RT, Jabs EW, Wu-Chou YH, Chen PK, Wang H, Ye X, Huang S, Yeow V, Chong SS, Jee SH, Shi B, Christensen K, Melbye M, Doheny KF, Pugh EW, Ling H, Castilla EE, Czeizel AE, Ma L, Field LL, Brody L, Pangilinan F, Mills JL, Molloy AM, Kirke PN, Scott JM, Arcos-Burgos M, Scott AF. [A genome-wide association study of cleft lip with and without cleft palate identifies risk variants near MAFB and ABCA4](https://www.nature.com/articles/ng.580). ***Nature Genetics***.

### 2009

1 Caporaso N, Gu F, Chatterjee N, **Jin SC**, Yu K, Yeager M, Chen C, Jacobs K, Wheeler W, Landi MT, Ziegler RG, Hunter DJ, Chanock S, Hankinson S, Kraft P, Bergen AW. [Genome-wide and candidate gene association study of cigarette smoking behaviors](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0004653). ***PLoS ONE***. 
